
# hw4:用物件導向的方式，建立屬於自己的normal scaler（標準化），其中要包含fit及transform功能

# 使用套件(sklearn)測試

In [82]:
from sklearn.preprocessing import StandardScaler

In [83]:
data = [[10, 15], [4, 8], [2, 9], [3, 14], [12, 23]]

In [84]:
scaler = StandardScaler()

In [85]:
print(scaler.fit(data))

StandardScaler(copy=True, with_mean=True, with_std=True)


In [86]:
print(scaler.mean_)

[  6.2  13.8]


In [87]:
print(scaler.var_)

[ 16.16  28.56]


In [88]:
print(scaler.transform(data))

[[ 0.94528533  0.22454436]
 [-0.54727045 -1.08529772]
 [-1.04478905 -0.89817743]
 [-0.79602975  0.03742406]
 [ 1.44280393  1.72150673]]


In [89]:
print(scaler.transform([[0, 1]]))

[[-1.54230764 -2.3951398 ]]


# 寫自己的StandradScaler

In [105]:
import numpy as np

In [134]:
#命名為 MeanVarScaler
class MeanVarScaler:
    def __init__(self):
        self.data_mean_ = None
        self.data_var_  = None
        self.data_std_  = None
        
    def fit(self,data):
        self.data_mean_ = np.mean(data, axis=0)
        self.data_var_  = np.var(data, axis=0)
        self.data_std_  = np.std(data, axis=0)
        
    def transform(self,data):
        nor_data = (np.array(data)-self.data_mean_)/np.std
        return nor_data
    
    def fit_transform(self,data):
        self.fit(data)
        return self.transform(data)

# 檢驗一下max、mean、std的數據

In [140]:
np.mean(data,axis=0)

array([  6.2,  13.8])

In [141]:
np.var(data,axis=0)

array([ 16.16,  28.56])

In [142]:
np.std(data, axis=0)

array([ 4.01995025,  5.34415569])

# 檢驗標準化後的數據

In [131]:
(np.array(data)-scaler.mean_)/np.sqrt(scaler.var_)

array([[ 0.94528533,  0.22454436],
       [-0.54727045, -1.08529772],
       [-1.04478905, -0.89817743],
       [-0.79602975,  0.03742406],
       [ 1.44280393,  1.72150673]])

# 看看套件與自己的StandradScaler結果是否一致

In [112]:
myscaler = MeanVarScaler()

In [113]:
data

[[10, 15], [4, 8], [2, 9], [3, 14], [12, 23]]

In [114]:
myscaler.fit(data)

In [143]:
myscaler.data_mean_

array([  6.2,  13.8])

In [144]:
myscaler.data_var_

array([ 16.16,  28.56])

In [145]:
myscaler.data_std_

array([ 4.01995025,  5.34415569])

In [118]:
myscaler.transform(data)

array([[ 0.94528533,  0.22454436],
       [-0.54727045, -1.08529772],
       [-1.04478905, -0.89817743],
       [-0.79602975,  0.03742406],
       [ 1.44280393,  1.72150673]])

# 結果一致!    wow~~

In [119]:
myscaler_new = MeanVarScaler()

In [120]:
myscaler_new.data_mean_

In [121]:
myscaler_new.fit_transform(data)

array([[ 0.94528533,  0.22454436],
       [-0.54727045, -1.08529772],
       [-1.04478905, -0.89817743],
       [-0.79602975,  0.03742406],
       [ 1.44280393,  1.72150673]])